package edu.hunau.base.support;

public enum ProvinceAndCityDatas {

	BEIJING1("北京", "beijing", "西城区"),
	BEIJING2("北京", "beijing", "崇文区"),
	BEIJING3("北京", "beijing", "宣武区"),
	BEIJING4("北京", "beijing", "海淀区"),
	BEIJING5("北京", "beijing", "丰台区"),
	BEIJING6("北京", "beijing", "石景山区"),
	BEIJING7("北京", "beijing", "门头勾区"),
	BEIJING8("北京", "beijing", "房山区"),
	BEIJING9("北京", "beijing", "顺义区"),
	BEIJING10("北京", "beijing", "昌平区"),
	BEIJING11("北京", "beijing", "大兴区"),
	BEIJING12("北京", "beijing", "平谷县"),
	BEIJING13("北京", "beijing", "怀柔县"),
	BEIJING14("北京", "beijing", "密云县"),
	BEIJING15("北京", "beijing", "延庆县"),	
	BEIJING16("北京", "beijing", "东城区"),
	
	SHANGHAI1("上海", "shanghai", "黄浦区"),
	SHANGHAI2("上海", "shanghai", "卢湾区"),
	SHANGHAI3("上海", "shanghai", "徐汇区"),
	SHANGHAI4("上海", "shanghai", "长宁区"),
	SHANGHAI5("上海", "shanghai", "静安区"),
	SHANGHAI6("上海", "shanghai", "普陀区"),
	SHANGHAI7("上海", "shanghai", "闸北区"),
	SHANGHAI8("上海", "shanghai", "虹口区"),
	SHANGHAI9("上海", "shanghai", "杨浦区"),
	SHANGHAI10("上海", "shanghai", "宝山区"),
	SHANGHAI11("上海", "shanghai", "闵行区"),
	SHANGHAI12("上海", "shanghai", "嘉定区"),
	SHANGHAI13("上海", "shanghai", "浦东新区"),
	SHANGHAI14("上海", "shanghai", "松江区"),
	SHANGHAI15("上海", "shanghai", "金山区"),
	SHANGHAI16("上海", "shanghai", "青浦区"),
	SHANGHAI17("上海", "shanghai", "南汇区"),
	SHANGHAI18("上海", "shanghai", "奉贤区"),
	SHANGHAI19("上海", "shanghai", "崇明县"),
	
	TIANJING1("天津","tianjing","和平区"),
	TIANJING2("天津","tianjing","河东区"),
	TIANJING3("天津","tianjing","河西区"),
	TIANJING4("天津","tianjing","南开区"),
	TIANJING5("天津","tianjing","河北区"),
	TIANJING6("天津","tianjing","红桥区"),
	TIANJING7("天津","tianjing","塘沽区"),
	TIANJING8("天津","tianjing","汉沽区"),
	TIANJING9("天津","tianjing","大港区"),
	TIANJING10("天津","tianjing","东丽区"),
	TIANJING11("天津","tianjing","西青区"),
	TIANJING12("天津","tianjing","北辰区"),
	TIANJING13("天津","tianjing","津南区"),
	TIANJING14("天津","tianjing","武清区"),
	TIANJING15("天津","tianjing","宝坻区"),
	TIANJING16("天津","tianjing","静海县"),
	TIANJING17("天津","tianjing","宁河县"),
	TIANJING18("天津","tianjing","蓟县"),
	
	CHONGQING1("重庆","","渝中区"),
	CHONGQING2("重庆","","大渡口区"),
	CHONGQING3("重庆","","江北区"),
	CHONGQING4("重庆","","沙坪坝区"),
	CHONGQING5("重庆","","九龙坡区"),
	CHONGQING6("重庆","","南岸区"),
	CHONGQING7("重庆","","北碚区"),
	CHONGQING8("重庆","","万盛区"),
	CHONGQING9("重庆","","双桥区"),
	CHONGQING10("重庆","","渝北区"),
	CHONGQING11("重庆","","巴南区"),
	CHONGQING12("重庆","","万州区"),
	CHONGQING13("重庆","","涪陵区"),
	CHONGQING14("重庆","","黔江区"),
	CHONGQING15("重庆","","永川市"),
	CHONGQING16("重庆","","合川市"),
	CHONGQING17("重庆","","江津市"),
	CHONGQING18("重庆","","南川市"),
	CHONGQING19("重庆","","长寿县"),
	CHONGQING20("重庆","","綦江县"),
	CHONGQING21("重庆","","潼南县"),
	CHONGQING22("重庆","","荣昌县"),
	CHONGQING23("重庆","","璧山区"),
	CHONGQING24("重庆","","大足县"),
	CHONGQING25("重庆","","铜梁县"),
	CHONGQING26("重庆","","梁平县"),
	CHONGQING27("重庆","","城口县"),
	CHONGQING28("重庆","","垫江县"),
	CHONGQING29("重庆","","武隆县"),
	CHONGQING30("重庆","","丰都县"),
	CHONGQING31("重庆","","奉节县"),
	CHONGQING32("重庆","","开县"),
	CHONGQING33("重庆","","云阳县"),
	CHONGQING34("重庆","","忠县"),
	CHONGQING35("重庆","","巫溪县"),
	CHONGQING36("重庆","","巫山县"),
	CHONGQING37("重庆","","石柱县"),
	CHONGQING38("重庆","","秀山县"),
	CHONGQING39("重庆","","酉阳县"),
	CHONGQING40("重庆","","彭水县"),
	
	GUANGDONG1("广东","","广州市"),
	GUANGDONG2("广东","","深圳市"),
	GUANGDONG3("广东","","珠海市"),
	GUANGDONG4("广东","","汕头市"),
	GUANGDONG5("广东","","韶关市"),
	GUANGDONG6("广东","","河源市"),
	GUANGDONG7("广东","","梅州市"),
	GUANGDONG8("广东","","惠州市"),
	GUANGDONG9("广东","","汕尾市"),
	GUANGDONG10("广东","","东莞市"),
	GUANGDONG11("广东","","中山市"),
	GUANGDONG12("广东","","江门市"),
	GUANGDONG13("广东","","佛山市"),
	GUANGDONG14("广东","","阳江市"),
	GUANGDONG15("广东","","湛江市"),
	GUANGDONG16("广东","","茂名市"),
	GUANGDONG17("广东","","肇庆市"),
	GUANGDONG18("广东","","清远市"),
	GUANGDONG19("广东","","潮州市"),
	GUANGDONG20("广东","","揭阳市"),
	GUANGDONG21("广东","","云浮市"),
	
	FUJIAN1("福建","","福州市"),
	FUJIAN2("福建","","厦门市"),
	FUJIAN3("福建","","三明市"),
	FUJIAN4("福建","","莆田市"),
	FUJIAN5("福建","","泉州市"),
	FUJIAN6("福建","","漳州市"),
	FUJIAN7("福建","","南平市"),
	FUJIAN8("福建","","龙岩市"),
	FUJIAN9("福建","","宁德市"),
	
	ZHEJIANG1("浙江","","杭州市"),
	ZHEJIANG2("浙江","","宁波市"),
	ZHEJIANG3("浙江","","温州市"),
	ZHEJIANG4("浙江","","嘉兴市"),
	ZHEJIANG5("浙江","","湖州市"),
	ZHEJIANG6("浙江","","绍兴市"),
	ZHEJIANG7("浙江","","金华市"),
	ZHEJIANG8("浙江","","衢州市"),
	ZHEJIANG9("浙江","","舟山市"),
	ZHEJIANG10("浙江","","台州市"),
	ZHEJIANG11("浙江","","丽水市"),
	
	JIANGSU1("江苏","","南京市"),
	JIANGSU2("江苏","","徐州市"),
	JIANGSU3("江苏","","连云港市"),
	JIANGSU4("江苏","","淮安市"),
	JIANGSU5("江苏","","宿迁市"),
	JIANGSU6("江苏","","盐城市"),
	JIANGSU7("江苏","","扬州市"),
	JIANGSU8("江苏","","秦州市"),
	JIANGSU9("江苏","","南通市"),
	JIANGSU10("江苏","","镇江市"),
	JIANGSU11("江苏","","常州市"),
	JIANGSU12("江苏","","无锡市"),
	JIANGSU13("江苏","","苏州市"),
	
	SHANDONG1("山东","","济南市"),
	SHANDONG2("山东","","青岛市"),
	SHANDONG3("山东","","淄博市"),
	SHANDONG4("山东","","枣庄市"),
	SHANDONG5("山东","","东营市"),
	SHANDONG6("山东","","潍坊市"),
	SHANDONG7("山东","","烟台市"),
	SHANDONG8("山东","","威海市"),
	SHANDONG9("山东","","济宁市"),
	SHANDONG10("山东","","泰安市"),
	SHANDONG11("山东","","日照市"),
	SHANDONG12("山东","","莱芜市"),
	SHANDONG13("山东","","德州市"),
	SHANDONG14("山东","","临沂市"),
	SHANDONG15("山东","","聊城市"),
	SHANDONG16("山东","","滨州市"),
	SHANDONG17("山东","","菏泽市"),	
	
	LIAOLING1("辽宁","","沈阳市"),
	LIAOLING2("辽宁","","大连市"),
	LIAOLING3("辽宁","","鞍山市"),
	LIAOLING4("辽宁","","抚顺市"),
	LIAOLING5("辽宁","","本溪市"),
	LIAOLING6("辽宁","","丹东市"),
	LIAOLING7("辽宁","","锦州市"),
	LIAOLING8("辽宁","","葫芦岛市"),
	LIAOLING9("辽宁","","营口市"),
	LIAOLING10("辽宁","","盘锦市"),
	LIAOLING11("辽宁","","阜新市"),
	LIAOLING12("辽宁","","辽阳市"),
	LIAOLING13("辽宁","","铁岭市"),
	LIAOLING14("辽宁","","朝阳市"),
	
	JIANGXI1("江西","","南昌市"),
	JIANGXI2("江西","","景德镇市"),
	JIANGXI3("江西","","萍乡市"),
	JIANGXI4("江西","","新余市"),
	JIANGXI5("江西","","九江市"),
	JIANGXI6("江西","","鹰潭市"),
	JIANGXI7("江西","","赣州市"),
	JIANGXI8("江西","","吉安市"),
	JIANGXI9("江西","","宜春市"),
	JIANGXI10("江西","","抚州市"),
	JIANGXI11("江西","","上饶市"),
	
	SICHUAN1("四川","","成都市"),
	SICHUAN2("四川","","自贡市"),
	SICHUAN3("四川","","攀枝花市"),
	SICHUAN4("四川","","泸州市"),
	SICHUAN5("四川","","德阳市"),
	SICHUAN6("四川","","绵阳市"),
	SICHUAN7("四川","","广元市"),
	SICHUAN8("四川","","遂宁市"),
	SICHUAN9("四川","","内江市"),
	SICHUAN10("四川","","乐山市"),
	SICHUAN11("四川","","南充市"),
	SICHUAN12("四川","","宜宾市"),
	SICHUAN13("四川","","广安市"),
	SICHUAN14("四川","","达州市"),
	SICHUAN15("四川","","巴中市"),
	SICHUAN16("四川","","雅安市"),
	SICHUAN17("四川","","眉山市"),
	SICHUAN18("四川","","资阳市"),
	SICHUAN19("四川","","阿坝州"),
	SICHUAN20("四川","","甘孜州"),
	SICHUAN21("四川","","凉山州"),
	
	SHANXI1("陕西","","西安市"),
	SHANXI2("陕西","","铜川市"),
	SHANXI3("陕西","","宝鸡市"),
	SHANXI4("陕西","","咸阳市"),
	SHANXI5("陕西","","渭南市"),
	SHANXI6("陕西","","延安市"),
	SHANXI7("陕西","","汉中市"),
	SHANXI8("陕西","","榆林市"),
	SHANXI9("陕西","","安康市"),
	SHANXI10("陕西","","商洛地区"),
	
	HUBEI1("湖北","","武汉市"),
	HUBEI2("湖北","","黄石市"),
	HUBEI3("湖北","","襄樊市"),
	HUBEI4("湖北","","十堰市"),
	HUBEI5("湖北","","荆州市"),
	HUBEI6("湖北","","宜昌市"),
	HUBEI7("湖北","","荆门市"),
	HUBEI8("湖北","","鄂州市"),
	HUBEI9("湖北","","孝感市"),
	HUBEI10("湖北","","黄冈市"),
	HUBEI11("湖北","","咸宁市"),
	HUBEI12("湖北","","随州市"),
	HUBEI13("湖北","","仙桃市"),
	HUBEI14("湖北","","天门市"),
	HUBEI15("湖北","","潜江市"),
	HUBEI16("湖北","","神农架"),
	HUBEI17("湖北","","恩施州"),
	
	HENAN1("河南","","郑州市"),
	HENAN2("河南","","开封市"),
	HENAN3("河南","","平顶山市"),
	HENAN4("河南","","焦作市"),
	HENAN5("河南","","鹤壁市"),
	HENAN6("河南","","新乡市"),
	HENAN7("河南","","安阳市"),
	HENAN8("河南","","濮阳市"),
	HENAN9("河南","","许昌市"),
	HENAN10("河南","","漯河市"),
	HENAN11("河南","","三门峡市"),
	HENAN12("河南","","南阳市"),
	HENAN13("河南","","商丘市"),
	HENAN14("河南","","信阳市"),
	HENAN15("河南","","周口市"),
	HENAN16("河南","","驻马店市"),
	HENAN17("河南","","济源市"),
	
	HEBEI1("河北","","石家庄"),
	HEBEI2("河北","","唐山市"),
	HEBEI3("河北","","秦皇岛市"),
	HEBEI4("河北","","邯郸市"),
	HEBEI5("河北","","邯郸市"),
	HEBEI6("河北","","保定市"),
	HEBEI7("河北","","张家口市"),
	HEBEI8("河北","","承德市"),
	HEBEI9("河北","","沧州市"),
	HEBEI10("河北","","廊坊市"),
	HEBEI11("河北","","衡水市"),
	
	SANXI1("山西","","太原市"),	
	SANXI2("山西","","大同市"),	
	SANXI3("山西","","阳泉市"),	
	SANXI4("山西","","长治市"),	
	SANXI5("山西","","晋城市"),	
	SANXI6("山西","","朔州市"),	
	SANXI7("山西","","晋中市"),	
	SANXI8("山西","","忻州市"),	
	SANXI9("山西","","临汾市	"),	
	SANXI10("山西","","运城市"),	
	SANXI11("山西","","吕梁地区"),
	
	NEIMENGGU1("内蒙古","","呼和浩特"),
	NEIMENGGU2("内蒙古","","包头市"),
	NEIMENGGU3("内蒙古","","乌海市"),
	NEIMENGGU4("内蒙古","","赤峰市"),
	NEIMENGGU5("内蒙古","","通辽市"),
	NEIMENGGU6("内蒙古","","鄂尔多斯"),
	NEIMENGGU7("内蒙古","","乌兰察布"),
	NEIMENGGU8("内蒙古","","锡林郭勒"),
	NEIMENGGU9("内蒙古","","呼伦贝尔"),
	NEIMENGGU10("内蒙古","","巴彦淖尔"),
	NEIMENGGU11("内蒙古","","阿拉善盟"),
	NEIMENGGU12("内蒙古","","兴安盟"),
	
	JILIN1("吉林","","长春市"),
	JILIN2("吉林","","吉林市"),
	JILIN3("吉林","","四平市"),
	JILIN4("吉林","","辽源市"),
	JILIN5("吉林","","通化市"),
	JILIN6("吉林","","白山市"),
	JILIN7("吉林","","松原市"),
	JILIN8("吉林","","白城市"),
	JILIN9("吉林","","延边州"),
	
	HEILONGJIANG1("黑龙江","","哈尔滨市"),
	HEILONGJIANG2("黑龙江","","齐齐哈尔"),
	HEILONGJIANG3("黑龙江","","鹤岗市"),
	HEILONGJIANG4("黑龙江","","双鸭山市"),
	HEILONGJIANG5("黑龙江","","鸡西市"),
	HEILONGJIANG6("黑龙江","","大庆市"),
	HEILONGJIANG7("黑龙江","","伊春市"),
	HEILONGJIANG8("黑龙江","","牡丹江市"),
	HEILONGJIANG9("黑龙江","","佳木斯市"),
	HEILONGJIANG10("黑龙江","","七台河市"),
	HEILONGJIANG11("黑龙江","","黑河市"),
	HEILONGJIANG12("黑龙江","","绥化市"),
	HEILONGJIANG13("黑龙江","","大兴安岭"),
	
	ANHUI1("安徽","","合肥市"),
	ANHUI2("安徽","","芜湖市"),
	ANHUI3("安徽","","蚌埠市"),
	ANHUI4("安徽","","淮南市"),
	ANHUI5("安徽","","马鞍山市"),
	ANHUI6("安徽","","淮北市"),
	ANHUI7("安徽","","铜陵市"),
	ANHUI8("安徽","","安庆市"),
	ANHUI9("安徽","","黄山市"),
	ANHUI10("安徽","","滁州市"),
	ANHUI11("安徽","","阜阳市"),
	ANHUI12("安徽","","六安市"),
	ANHUI13("安徽","","亳州市"),
	ANHUI14("安徽","","宣城市"),
	ANHUI15("安徽","","池州市"),
	
	HUNAN1("湖南","","长沙市"),
	HUNAN2("湖南","","株州市"),
	HUNAN3("湖南","","湘潭市"),
	HUNAN4("湖南","","衡阳市"),
	HUNAN5("湖南","","邵阳市"),
	HUNAN6("湖南","","岳阳市"),
	HUNAN7("湖南","","常德市"),
	HUNAN8("湖南","","张家界市"),
	HUNAN9("湖南","","益阳市"),
	HUNAN10("湖南","","郴州市"),
	HUNAN11("湖南","","永州市"),
	HUNAN12("湖南","","怀化市"),
	HUNAN13("湖南","","娄底市"),
	HUNAN14("湖南","","湘西州"),
	
	GUANGXI1("广西","","南宁市"),
	GUANGXI2("广西","","柳州市"),
	GUANGXI3("广西","","桂林市"),
	GUANGXI4("广西","","梧州市"),
	GUANGXI5("广西","","北海市"),
	GUANGXI6("广西","","防城港市"),
	GUANGXI7("广西","","钦州市"),
	GUANGXI8("广西","","贵港市"),
	GUANGXI9("广西","","玉林市"),
	GUANGXI10("广西","","南宁地区"),
	GUANGXI11("广西","","柳州地区"),
	GUANGXI12("广西","","贺州地区"),
	GUANGXI13("广西","","百色地区"),
	GUANGXI14("广西","","河池地区"),
	
	HAINAN1("海南市","","海口市"),
	HAINAN2("海南市","","三亚市"),
	HAINAN3("海南市","","五指山市"),
	HAINAN4("海南市","","琼海市"),
	HAINAN5("海南市","","儋州市"),
	HAINAN6("海南市","","琼山市"),
	HAINAN7("海南市","","文昌市"),
	HAINAN8("海南市","","万宁市"),
	HAINAN9("海南市","","东方市"),
	HAINAN10("海南市","","澄迈县"),
	HAINAN11("海南市","","定安县"),
	HAINAN12("海南市","","屯昌县"),
	HAINAN13("海南市","","临高县"),
	HAINAN14("海南市","","白沙县"),
	HAINAN15("海南市","","昌江县"),
	HAINAN16("海南市","","乐东县"),
	HAINAN17("海南市","","陵水县"),
	HAINAN18("海南市","","保亭县"),
	HAINAN19("海南市","","琼中县"),
	
	YUNNAN1("云南","","昆明市"),
	YUNNAN2("云南","","曲靖市"),
	YUNNAN3("云南","","玉溪市"),
	YUNNAN4("云南","","保山市"),
	YUNNAN5("云南","","昭通市"),
	YUNNAN6("云南","","思茅地区"),
	YUNNAN7("云南","","临沧地区"),
	YUNNAN8("云南","","丽江地区"),
	YUNNAN9("云南","","文山州"),
	YUNNAN10("云南","","红河州"),
	YUNNAN11("云南","","西双版纳"),
	YUNNAN12("云南","","楚雄州"),
	YUNNAN13("云南","","大理州"),	
	YUNNAN14("云南","","德宏州"),
	YUNNAN15("云南","","怒江州"),
	YUNNAN16("云南","","迪庆州"),
	
	GUIZHOU1("贵州","","贵阳市"),
	GUIZHOU2("贵州","","六盘水市"),
	GUIZHOU3("贵州","","遵义市"),
	GUIZHOU4("贵州","","安顺市"),
	GUIZHOU5("贵州","","铜仁地区"),
	GUIZHOU6("贵州","","毕节地区"),
	GUIZHOU7("贵州","","黔西南州"),
	GUIZHOU8("贵州","","黔东南州"),
	GUIZHOU9("贵州","","黔南州"),
	
	XIZHANG1("西藏","","拉萨市"),
	XIZHANG2("西藏","","那曲地区"),
	XIZHANG3("西藏","","昌都地区"),
	XIZHANG4("西藏","","山南地区"),
	XIZHANG5("西藏","","日喀则"),
	XIZHANG6("西藏","","阿里地区"),
	XIZHANG7("西藏","","林芝地区"),
	
	GANSU("甘肃","","兰州市"),
	GANSU2("甘肃","","金昌市"),
	GANSU3("甘肃","","白银市"),
	GANSU4("甘肃","","天水市"),
	GANSU5("甘肃","","嘉峪关市"),
	GANSU6("甘肃","","武威市"),
	GANSU7("甘肃","","定西地区"),
	GANSU8("甘肃","","平凉地区"),
	GANSU9("甘肃","","庆阳地区"),
	GANSU10("甘肃","","陇南地区"),
	GANSU11("甘肃","","张掖地区"),
	GANSU12("甘肃","","酒泉地区"),
	GANSU13("甘肃","","甘南州"),
	GANSU14("甘肃","","临夏州"),
	
	NINGXIA1("宁夏","","银川市"),
	NINGXIA2("宁夏","","石嘴山市"),
	NINGXIA3("宁夏","","吴忠市"),
	NINGXIA4("宁夏","","固原市"),

	QINGHAI1("青海","","西宁市"),
	QINGHAI2("青海","","海东地区"),
	QINGHAI3("青海","","海北州"),
	QINGHAI4("青海","","黄南州"),
	QINGHAI5("青海","","海南州"),
	QINGHAI6("青海","","果洛州"),
	QINGHAI7("青海","","玉树州"),
	QINGHAI8("青海","","海西州"),

	XINGJIANG1("新疆","","乌鲁木齐"),
	XINGJIANG2("新疆","","克拉玛依"),
	XINGJIANG3("新疆","","石河子市"),
	XINGJIANG4("新疆","","吐鲁番"),
	XINGJIANG5("新疆","","哈密地区"),
	XINGJIANG6("新疆","","和田地区"),
	XINGJIANG7("新疆","","阿克苏"),
	XINGJIANG8("新疆","","喀什地区"),
	XINGJIANG9("新疆","","克孜勒苏"),
	XINGJIANG10("新疆","","巴音郭楞"),
	XINGJIANG11("新疆","","昌吉州"),
	XINGJIANG12("新疆","","博尔塔拉"),
	XINGJIANG13("新疆","","伊犁州"),
	
	XIANGGANG("香港","xianggang",null),
	AOMEN("澳门","aomen",null),
	TAIWAN("台湾","taiwan",null),
	HAIWAI("海外","haiwai",null)
	;
	
	private String province;
	private String province_short;
	private String city;

	private ProvinceAndCityDatas(String province, String province_short, String city) {
		this.province = province;
		this.province_short = province_short;
		this.city = city;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getProvince_short() {
		return province_short;
	}

	public void setProvince_short(String province_short) {
		this.province_short = province_short;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}
}
